server:
  #指定运行端口
  port: 8002

spring:
  application:
    name: eureka-server2 # 指定服务名称
eureka:
  instance:
    hostname: eureka-server2 #指定主机地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
#  server:
#    enable-self-preservation: false #关闭保护模式