server:
  #指定运行端口
  port: 8001

spring:
  application:
    name: eureka-server1 # 指定服务名称
eureka:
  instance:
    hostname: eureka-server1 #指定主机地址
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/ #配置注册中心地址,注意后边的eureka并不是eureka服务的名称，而是固定值，只要是eureka服务器就好
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
#  server:
#    enable-self-preservation: false #关闭保护模式
